apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-sops-plugin
  namespace: argocd
data:
  sops.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops
    spec:
      version: v1.0
      generate:
        command: ["sh", "-c"]
        args: ["set -e; for i in $(find . -type f -name '*.yaml' | grep -v 'Chart.yaml\|values.yaml\|templates/'); do sops --decrypt $i >> "decorated_$(basename $i)"; done; cat $(find . -name 'decorated_*.yaml')"]
      discover:
        find:
          command: ["sh", "-c"]
          args: ["find . -name .sops.yaml -exec dirname {} \;"]
