apiVersion: v1
kind: Secret
metadata:
  name: sops-age-key
  namespace: argocd
type: Opaque
stringData:
  # Your age private key should be placed in a file named 'keys.txt'
  keys.txt: |
    AGE-SECRET-KEY-....
