apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: wallabag
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/roadhouse/helm-wallabag.git
        targetRevision: main
        path: .
        helm:
            values: ENC[AES256_GCM,data:yXJSCK+dNYJc0KKhcvh3ZOi/7do1UemdfPRUv3SQurhgM4VY2uV+6jFSA79NHt1tPMDku8BrQYqK+XAiJ90/hV0kZXNUwJQ7C1nvPLBNVmlKGqzLj4hmOxWEt+8L,iv:/9pemSl9DDyS6iMfxsCOB0bEVA5ZbrzQ2sQY8teAGP4=,tag:szXVxR7b4zd1VucklnXSkA==,type:str]
    destination:
        server: https://kubernetes.default.svc
        namespace: wallabag
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnm82r8s3f55w2ysjm0xm79ludu05pzefrdv2p8pzqefd47nh4xqne0jju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWnYwd2tyY0xuTzg3ajQ3
            bGVycitrNHF1MUE1NzhXVjBhN2pla1g4UEEwClloemV2bjRHUzFjZzdUdk16WGY5
            YlJ2VWhMS3UzTElySnlCa2Q0TWpQeFkKLS0tIFFyeXJEcUN2VGQva3U5TDJSR251
            aDM3Y3RTQWlvQ1dsSXBLRjZRMnV1NmsKgNQssx5uTpxqgBsN7jNUGsOSvBrDzxdZ
            jLuhBmjH1/I4c2/glZ7YfDE/TDnGsdwXRcFAhWIJON7VHLKOc1xBjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-12T19:23:50Z"
    mac: ENC[AES256_GCM,data:viErX+IQOzFJa64B+XVl7rkbgATEj0QsS9/D0ho8o8Z5BUrrCsYxlw4WnuFJObys+3G/zibMgNyoQkvD4cCE7+AQwYKV1/Gx0rJIQ1PughkjcNGYR0Y92BeXQG1uKHvO2+mNYaEpmH01ZXgTQMAPkd7+bVF97DFGhUO0zIf4eDo=,iv:AD86Q3AeeKoaBrL5Kajq88mHSEiK1exXzFxtu7uZ65A=,tag:qjXfR9FPPHwgbv3oQoAQrg==,type:str]
    pgp: []
    encrypted_regex: ^(hostPath|DOMAIN_NAME|values)$
    version: 3.7.3
